const fields = {
    name: {
        name: 'name',
        label: 'Name',
        type: 'text',
        required: true,
    },
    email: {
        name: 'email',
        label: 'Email',
        type: 'email',
        required: true,
    },
    password: {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
    },
    passwordConfirmation: {
        name: 'passwordConfirmation',
        label: 'Password Confirmation',
        type: 'password',
        required: true,
    },
    username: {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
    },
    description: {
        name: 'description',
        label: 'Description',
        type: 'text',
        required: true,
    },
    title: {
        name: 'title',
        label: 'Title',
        type: 'text',
        required: true,
    },
    content: {
        name: 'content',
        label: 'Content',
        type: 'text',
        required: true,
    },
    tags: {
        name: 'tags',
        label: 'Tags',
        type: 'text',
        required: true,
    },
    image: {
        name: 'image',
        label: 'Image',
        type: 'text',
        required: true,
    },
    link: {
        name: 'link',
        label: 'Link',
        type: 'text',
        required: true,
    },
    status: {
        name: 'status',
        label: 'Status',
        type: 'text',
        required: true,
    },
    type: {
        name: 'type',
        label: 'Type',
        type: 'text',
        required: true,
    },
    category: {
        name: 'category',
        label: 'Category',
        type: 'text',
        required: true,
    },
    price: {
        name: 'price',
        label: 'Price',
        type: 'text',
        required: true,
    },
    currency: {
        name: 'currency',
        label: 'Currency',
        type: 'text',
        required: true,
    },
    quantity: {
        name: 'quantity',
        label: 'Quantity',
        type: 'text',
        required: true,
    },
    weight: {
        name: 'weight',
        label: 'Weight',
        type: 'text',
        required: true,
    },
    length: {
        name: 'length',
        label: 'Length',
        type: 'text',
        required: true,
    },
    width: {
        name: 'width',
        label: 'Width',
        type: 'text',
        required: true,
    },
    height: {
        name: 'height',
        label: 'Height',
        type: 'text',
        required: true,
    },
    color: {
        name: 'color',
        label: 'Color',
        type: 'text',
        required: true,
    },
    size: {
        name: 'size',
        label: 'Size',
        type: 'text',
        required: true,
    },
    material: {
        name: 'material',
        label: 'Material',
        type: 'text',
        required: true,
    },
    brand: {
        name: 'brand',
        label: 'Brand',
        type: 'text',
        required: true,
    },
    model: {
        name: 'model',
        label: 'Model',
        type: 'text',
        required: true,
    },
    manufacturer: {
        name: 'manufacturer',
        label: 'Manufacturer',
        type: 'text',
        required: true,
    },
    provider: {
        name: 'provider',
        label: 'Provider',
        type: 'text',
        required: true,
    },
    supplier: {
        name: 'supplier',
        label: 'Supplier',
        type: 'text',
        required: true,
    },
    origin: {
        name: 'origin',
        label: 'Origin',
        type: 'text',
        required: true,
    },
    destination: {
        name: 'destination',
        label: 'Destination',
        type: 'text',
        required: true,
    },
    address: {
        name: 'address',
        label: 'Address',
        type: 'text',
        required: true,
    },
    city: {
        name: 'city',
        label: 'City',
        type: 'text',
        required: true,
    },
    state: {
        name: 'state',
        label: 'State',
        type: 'text',
        required: true,
    },
    country: {
        name: 'country',
        label: 'Country',
        type: 'text',
        required: true,
    },
    zipcode: {
        name: 'zipcode',
        label: 'Zipcode',
        type: 'text',
        required: true,
    },
    phone: {
        name: 'phone',
        label: 'Phone',
        type: 'text',
        required: true,
    },
    mobile: {
        name: 'mobile',
        label: 'Mobile',
        type: 'text',
        required: true,
    },
    website: {
        name: 'website',
        label: 'Website',
        type: 'text',
        required: true,
    },
    facebook: {
        name: 'facebook',
        label: 'Facebook',
        type: 'text',
        required: true,
    },
    twitter: {
        name: 'twitter',
        label: 'Twitter',
        type: 'text',
        required: true,
    },
    instagram: {
        name: 'instagram',
        label: 'Instagram',
        type: 'text',
        required: true,
    },
    youtube: {
        name: 'youtube',
        label: 'Youtube',
        type: 'text',
        required: true,
    },
    linkedin: {
        name: 'linkedin',
        label: 'Linkedin',
        type: 'text',
        required: true,
    },
};

module.exports = {
    fields,
};