const inputTypes = {
    text: 'text',
    number: 'number',
    email: 'email',
    password: 'password',
    date: 'date',
    checkbox: 'checkbox',
    radio: 'radio',
    select: 'select',
    textarea: 'textarea',
    file: 'file',
    button: 'button',
    submit: 'submit',
    reset: 'reset',
    hidden: 'hidden',
    image: 'image',
    range: 'range',
    color: 'color',
    tel: 'tel',
    url: 'url',
    search: 'search',
    time: 'time',
    datetime: 'datetime',
    month: 'month',
    week: 'week',
    datetimeLocal: 'datetime-local',
    selectMultiple: 'select-multiple',
    selectOne: 'select-one',
    selectOneOrMore: 'select-one-or-more',
    selectMultipleOrMore: 'select-multiple-or-more',
};

export { inputTypes };