const variantByStatus = {
    success: 'success',
    error: 'danger',
    warning: 'warning',
    info: 'info',
    default: 'default',
    primary: 'primary',
    secondary: 'secondary',
    accent: 'accent',
    neutral: 'neutral',
    muted: 'muted',
    white: 'white',
    black: 'black',
    dark: 'dark',
    light: 'light',
    link: 'link',
    infoLight: 'info-light',
    infoDark: 'info-dark',
    successLight: 'success-light',
    successDark: 'success-dark',
    warningLight: 'warning-light',
    warningDark: 'warning-dark',
    errorLight: 'error-light',
    errorDark: 'error-dark',
    defaultLight: 'default-light',
    defaultDark: 'default-dark',
    primaryLight: 'primary-light',
    primaryDark: 'primary-dark',
    secondaryLight: 'secondary-light',
    secondaryDark: 'secondary-dark',
    accentLight: 'accent-light',
    accentDark: 'accent-dark',
    neutralLight: 'neutral-light',
    neutralDark: 'neutral-dark',
    mutedLight: 'muted-light',
    mutedDark: 'muted-dark',
};

export { variantByStatus };